### ISSUE TITLE
like logic

### ISSUE THREAD

**Issue by hoit1302** [February-of-Spring/EDSC-server#5]
- 게시글에 좋아요를 할 수 있다.
- 내가 좋아요한 게시글을 모아볼 수 있다.
<br>

- [ ] 어떻게 로그인된 사용자를 받아오는가.
- [ ] 회원가입하지 않은 사람은 좋아요를 할 수 없는가.

**Comment by jeongwon-iee** [comment]
- 로그인 후 deviceToken 값으로 사용자 받아오기
- 회원가입 하지 않은 사람은 좋아요를 할 수 없다.
